[utils]
console_indent = '...'


[db_sqlite]
db_dir='db'
db_file='db_data.sqlite3'


[excel]
result_dir='result_excel'


[db]
host ='127.0.0.1'
port = 5432
db_name = 'db_name'
db_user = 'db_user'
db_password = 'db_password'
